
server:
  port: 8082

dubbo:
  registry:
    protocol: spring-cloud
    address: nacos://127.0.0.1:8848/?namespace=dubbo-namespace&username=pcs&password=Bmht@123
  scan:
    base-packages: com.ckun.dubbo
  protocol:
    name: dubbo
    port: 11001


